labels:
  - name: 'release:major'
    color: 'b60205'
    description: 'Trigger a major version bump'
  - name: 'release:minor'
    color: '0e8a16'
    description: 'Trigger a minor version bump'
  - name: 'release:patch'
    color: '1d76db'
    description: 'Trigger a patch version bump'
  - name: 'feat'
    color: 'a2eeef'
    description: 'New feature'
  - name: 'fix'
    color: 'd73a4a'
    description: 'Bug fix'
  - name: 'docs'
    color: '0075ca'
    description: 'Documentation changes'
  - name: 'perf'
    color: 'c2e0c6'
    description: 'Performance improvements'
  - name: 'refactor'
    color: 'c5def5'
    description: 'Refactoring'
  - name: 'test'
    color: 'e4e669'
    description: 'Testing only'
  - name: 'chore'
    color: 'ffffff'
    description: 'Maintenance chores'
