name-template: 'v$NEXT_PATCH_VERSION'
tag-template: 'v$NEXT_PATCH_VERSION'
categories:
  - title: '🚀 Features'
    labels: ['feat', 'feature', 'release:minor']
  - title: '🐛 Bug Fixes'
    labels: ['fix', 'bug', 'release:patch']
  - title: '⚙️ Performance'
    labels: ['perf']
  - title: '🧰 Maintenance'
    labels: ['chore', 'refactor']
  - title: '🧪 Tests'
    labels: ['test']
  - title: '📝 Documentation'
    labels: ['docs']
change-template: '- $TITLE (#$NUMBER) by @$AUTHOR'
version-resolver:
  major:
    labels: ['release:major']
  minor:
    labels: ['release:minor', 'feat', 'feature']
  patch:
    labels: ['release:patch', 'fix', 'bug', 'perf', 'refactor', 'docs', 'test', 'chore']
  default: patch
autolabeler:
  - label: 'docs'
    files: ['**/*.md']
  - label: 'test'
    files: ['tests/**']
  - label: 'chore'
    files: ['.github/**']
  - label: 'feat'
    branch:
      - '/feat\/.+/'
  - label: 'fix'
    branch:
      - '/fix\/.+/'
template: |
  ## What’s Changed
  $CHANGES
